[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Mike Tang <daogangtang@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10"
hex = "0.3"

[[bin]]
name = "hex2base64"
path = "src/hex2base64.rs"




